In [1]:
import pandas as pd
import numpy as np
from func import clean_df

# model imports
from keras.models import Sequential
from keras.layers import Dense, Dropout
import keras.layers as layers

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [2]:
data = pd.read_csv('./dataset/data.csv') # read the dataset
data = clean_df(df=data, drop_columns=['text','date']) # clean the dataset

print(len(data))
print(data['subject'].unique())
data.sample(10)

Rows dropped: 610/39942 (1.53%)
39332
['politicsNews' 'worldnews' 'News' 'politics' 'Government News'
 'left-news']

,label,title,subject,reporter,content
14077,1,"Iran Guards ready to help rebuild Syria, Hezbo...",worldnews,ANKARA (Reuters),Iran s Revolutionary Guards are ready to help ...
2650,1,Republicans meet late into night as Trump dema...,politicsNews,WASHINGTON (Reuters),Republicans struggling to agree on healthcare ...
16610,1,French Catalans offer Puigdemont luxury safe-h...,worldnews,PARIS (Reuters),French Catalans have a villa with a swimming p...
21490,0,PREDICTION: White House Lies Will Force Deput...,News,Unknown,The first reason the White House gave for Pres...
19665,1,UK's May says foreign minister Johnson 'doing ...,worldnews,LONDON (Reuters),British Prime Minister Theresa May backed her ...
18793,1,Lebanon sentences Islamist cleric to death for...,worldnews,BEIRUT (Reuters),A hardline Sunni Muslim cleric was sentenced t...
32961,0,TRUMP SPOKESPERSON THREATENS Trump Rally On Ma...,politics,Unknown,If the Trump campaign arranges a rally while O...
3659,1,Netanyahu: hope Trump visit will be 'milestone...,politicsNews,TEL AVIV (Reuters),Israeli Prime Minister Benjamin Netanyahu said...
33929,0,AUSTRIAN Schools Are Being Radicalized By Youn...,politics,Unknown,This story is a perfect example of how Muslim ...
27462,0,Donald Trump Just Posted The Weirdest Ad You’...,News,Unknown,Everyone knows that Republican front runner Do...

In [4]:
# mask = pd.to_datetime(data['date'], format='mixed', errors='coerce').isna()
# print(data[mask]['date'].value_counts().head(20))

In [5]:
data.sample(10)

,label,title,subject,reporter,content
2379,1,Mexico sets out NAFTA goals ahead of re-negoti...,politicsNews,MEXICO CITY (Reuters),Mexico has set out its goals for an upcoming r...
29397,0,LOL! SARAH PALIN Has EPIC Response When MSNBC ...,politics,Unknown,MSNBC reporter Kasie Hunt began her segment on...
10608,1,Sanders supporters' courtship of Clinton super...,politicsNews,(Reuters),Backers of Democratic presidential contender B...
35013,0,(VIDEO) WOW! THIS RACIST STATEMENT FROM JEB BU...,politics,Unknown,Stereotype much? Wow! This entire statement is...
5153,1,Governors met on Obamacare replacement plan wi...,politicsNews,WASHINGTON (Reuters),Ten state governors seeking to avoid millions ...
15203,1,"Zimbabwe renames main airport after Mugabe, pl...",worldnews,HARARE (Reuters),Zimbabwe will upgrade its main airport at a co...
15622,1,Center-right leads narrowly in Sicily regional...,worldnews,"PALERMO, Italy (Reuters)",Silvio Berlusconi s center-right coalition has...
4873,1,Republican healthcare bill would harm state fi...,politicsNews,SAN FRANCISCO (Reuters),The Republican-proposed bill to replace Obamac...
459,1,Factbox: Trump on Twitter (November 29) - Matt...,politicsNews,Unknown,The following statements were posted to the ve...
35334,0,HILLARY CLINTON STREET ART APPEARS IN LOS ANGE...,politics,Unknown,You know those really tacky air fresheners you...

In [6]:
# split the dataset into training and testing sets
x_data_lst = ['title', 'content']

In [ ]:
model = Sequential([])