In [1]:
import pandas as pd
from func import clean_df

In [2]:
data = pd.read_csv('./dataset/data.csv')

print(len(data))
print(data['subject'].unique())
data.sample(10)

39942
<StringArray>
['politicsNews', 'worldnews', 'News', 'politics', 'Government News',
 'left-news']
Length: 6, dtype: str

,label,title,text,subject,date
29295,0,JUST IN: VIDEO SHOWS Obama State Department Te...,The stock market lost over 350 points after AB...,politics,"Dec 2, 2017"
11199,1,Obama unveils wage insurance plan to spur job ...,WASHINGTON - U.S. President Barack Obama on Sa...,politicsNews,"January 16, 2016"
29288,0,CONFUSED PROTESTERS Swarm Outside Trump NYC Fu...,The protesters in NYC must be confused They ye...,politics,"Dec 3, 2017"
12042,1,"Gunmen seize building in Afghan capital, firin...",KABUL (Reuters) - A group of armed men seized ...,worldnews,"December 18, 2017"
28860,0,Gotta Love It When Idiot Conservatives Accide...,Conservatives alongside right-wing media outle...,News,"January 9, 2016"
25766,0,Democrat Hilariously Mocks Paul Ryan During H...,"On Wednesday, the Democratic party staged a po...",News,"June 22, 2016"
24379,0,BUSTED: Donald Trump Screwed Over American St...,Donald Trump claims he will make America grea...,News,"October 3, 2016"
6418,1,Trump rally makes stock options great again fo...,BOSTON (Reuters) - Donald Trump once described...,politicsNews,"January 11, 2017"
19296,1,Factbox: How U.S. multinationals in Puerto Ric...,(Reuters) - Hurricane Maria has devastated the...,worldnews,"September 22, 2017"
14495,1,Iraqi forces recapture last Islamic State-held...,BAGHDAD (Reuters) - Iraqi forces on Friday cap...,worldnews,"November 17, 2017"

In [3]:
data = clean_df(df=data)
data.sample(10)

,label,title,subject,date,reporter,content
4997,1,Highlights: The Trump presidency on March 12 a...,politicsNews,"March 12, 2017",(Reuters),Highlights of the day for U.S. President Donal...
37338,0,AMTRAK FACTS AND WHY AMERICANS SHOULDN’T TRUST...,Government News,"May 15, 2015",Unknown,The Democrats didn t waste any time pushing fo...
23500,0,Major City SLAPS Greedy CEOs Like Trump With ...,News,"December 8, 2016",Unknown,This is HUGE news!The city council of Portland...
23311,0,President Obama Calls Out Fox News For Creati...,News,"December 22, 2016",Unknown,Fox News worked for eight years to vilify Pres...
28248,0,Someone Just Tried To Perform An Exorcism On ...,News,"February 8, 2016",Unknown,While Ted Cruz would say that he is possessed ...
34456,0,REPORTER ASKS: Will Obama Golf Instead of Atte...,politics,"Feb 18, 2016",Unknown,BRAVE GUY!
27860,0,Remember When Bernie Sanders Was Literally Sl...,News,"February 25, 2016",Unknown,During the 1988 Democratic Presidential Primar...
16092,1,"U.S., Qatar agree to further curbs on terroris...",worldnews,"October 30, 2017",DOHA (Reuters),Qatar has agreed to strengthen counter-terrori...
20262,0,Anti-Abortion Republican Cheated And Tried To...,News,"October 3, 2017",Unknown,A text message which was sent in January to U....
36957,0,PROOF THAT TRUMP WAS DEAD ON: NJ Rooftop Parti...,Government News,"Nov 23, 2015",Unknown,Donald Trump was right again! This is yet anot...