In [15]:
import pandas as pd

In [16]:
data = pd.read_csv('./dataset/data.csv')

print(len(data))
print(data['subject'].unique())
data.sample(10)

39942
<StringArray>
['politicsNews', 'worldnews', 'News', 'politics', 'Government News',
 'left-news']
Length: 6, dtype: str

,label,title,text,subject,date
28466,0,Susan Sarandon Brutally Slams Trump: He’s Lik...,Award-winning actress and political activist S...,News,"January 29, 2016"
20571,0,Charlottesville Vice-Mayor Responds To Trump’...,As more time passes after the violent riots re...,News,"August 13, 2017"
7465,1,"Renzi congratulates Trump, says Italy friendsh...",ROME (Reuters) - Italian Prime Minister Matteo...,politicsNews,"November 9, 2016"
11039,1,Kerry says can't comment on content of Clinton...,QUEBEC CITY (Reuters) - U.S. Secretary of Stat...,politicsNews,"January 29, 2016"
32519,0,"LOL! WHEN YOUR CLIENT, Hillary Clinton Is Unde...",,politics,"Nov 2, 2016"
8397,1,Brexit campaigner Farage says to address Trump...,"LONDON (Reuters) - Nigel Farage, an anti-immig...",politicsNews,"August 24, 2016"
14678,1,Thailand plans joint arms factory with China,BANGKOK (Reuters) - Thailand s defense technol...,worldnews,"November 16, 2017"
38722,0,TRUMP DELIVERS BARN BURNER OF A SPEECH: “Media...,President Trump skipped the White House Corres...,left-news,"Apr 30, 2017"
19592,1,Turkey threatens sanctions over Kurdish indepe...,"HABUR BORDER CROSSING, Turkey (Reuters) - Turk...",worldnews,"September 20, 2017"
12287,1,Undercover Israeli agents in action,"EL-BIREH, West Bank (Reuters) - Reuters photog...",worldnews,"December 14, 2017"

In [17]:
def clean_text(text):
    # remove leading and trailing whitespace
    text = text.strip()
    # replace multiple spaces with a single space
    text = ' '.join(text.split())
    return text

# create a new column 'reporter' by extracting all before ' - ' from the 'text' column if within first 5 words
for index, row in data.iterrows():
    text = row['text']
    text = clean_text(text)
    words = text.split()
    # check if ' - ' is within the first 5 words
    if ' - ' in text and text.index(' - ') < len(' '.join(words[:5])):
        data.at[index, 'reporter'] = text.split(' - ')[0]
    else: data.at[index, 'reporter'] = "Unknown"

# print(data['reporter'].unique())

# create a new column 'content' by extracting all after ' - ' from the 'text' column
for index, row in data.iterrows():
    text = row['text']
    words = text.split()
    # check if ' - ' is within the first 5 words
    if ' - ' in text and text.index(' - ') < len(' '.join(words[:5])):
        data.at[index, 'content'] = text.split(' - ')[1]
    else: data.at[index, 'content'] = text

# delete the 'text' column
data = data.drop(columns=['text'])

In [ ]:
def clean_df(df: pd.DataFrame) -> pd.DataFrame:

    def add_reporter(df: pd.DataFrame) -> pd.DataFrame:
        for index, row in df.iterrows():
            text = row['text']
            text = clean_text(text)
            words = text.split()
            # check if ' - ' is within the first 5 words
        if ' - ' in text and text.index(' - ') < len(' '.join(words[:5])):
            df.at[index, 'reporter'] = text.split(' - ')[0]
        else: df.at[index, 'reporter'] = "Unknown"
        return df
    
    def add_content(df: pd.DataFrame) -> pd.DataFrame:
        for index, row in df.iterrows():
            text = row['text']
            words = text.split()
            # check if ' - ' is within the first 5 words
        if ' - ' in text and text.index(' - ') < len(' '.join(words[:5])):
            df.at[index, 'content'] = text.split(' - ')[1]
        else: df.at[index, 'content'] = text
        return df
    
    def drop_text(df: pd.DataFrame) -> pd.DataFrame:
        df = df.drop(columns=['text'])
        return df
    
    df = add_reporter(df)
    df = add_content(df)
    df = drop_text(df)
    return df

In [18]:
data.sample(10)

,label,title,subject,date,reporter,content
23490,0,Obama Probing Putin: Orders Review Of Russian...,News,"December 9, 2016",Unknown,President Obama has ordered a full review of...
25702,0,OR Police Chief ‘Accidentally’ Shot Camping B...,News,"June 27, 2016",Unknown,"Portland, Oregon Police Chief Larry O Dea is e..."
12435,1,Turkish teachers linked to Erdogan foe detaine...,worldnews,"December 12, 2017",KABUL (Reuters),One Afghan and three Turkish teachers linked t...
8014,1,Trump's debate sniffs take off on social media,politicsNews,"September 27, 2016",NEW YORK (Reuters),Republican White House candidate Donald Trump ...
4121,1,Trump visits wounded U.S. service members at m...,politicsNews,"April 22, 2017","BETHESDA, Md. (Reuters)",President Donald Trump visited wounded U.S. se...
3203,1,Trump to deliver statement on shooting of lawm...,politicsNews,"June 14, 2017",WASHINGTON (Reuters),U.S. President Donald Trump will deliver a sta...
17204,1,U.S. official says not ruling out eventual dir...,worldnews,"October 17, 2017",TOKYO/UNITED NATIONS (Reuters),The United States is not ruling out the eventu...
24939,0,SCAMPAIGN: Here’s How GOP Donors Are Making T...,News,"August 23, 2016",Unknown,Donald Trump is making a lot of money thanks t...
9281,1,"Japan, South Korea to set up direct line betwe...",politicsNews,"June 4, 2016",SINGAPORE (Reuters),Japanese Defence Minister Gen Nakatani said on...
20225,0,White Pro-Trump Pastor Tries To Rap Attack On...,News,"October 12, 2017",Unknown,Hahahahahahahaha. Hahahahahahahahahahahahahaha...

['Japanese Defence Minister Gen Nakatani said on Saturday that Japan and South Korea agreed to expand an emergency communication system between their defense ministries, including adding a new direct line between defense ministers. Tensions have been high in the region since early January when North Korea conducted its fourth nuclear test. It has followed that with a satellite launch and tests of various missiles, most recently a failed launch on Tuesday. “What it means is that we will make use of phones for emergency communication, when security-related emergencies such as a missile launch occur, and communication and coordination between the defense authorities of the two countries are needed,” Nakatani told reporters at the Shangri-La Dialogue, a regional security forum in Singapore. He said such emergency phone lines would be expanded to include a new direct link between the two countries’ defense ministers.  Nakatani said talks would continue on sharing and safeguarding sensitive information on Pyongyang’s missile and nuclear programs.  Under the framework, South Korea would pass relevant information to the United States, with which Seoul already has a legally-binding pact to share and safeguard intelligence called General Security of Military Information Agreement (GSOMIA). The United States would then pass the information on to Japan. It would work similarly the other way around since the United States has also signed a GSOMIA with Japan.  Some South Koreans have voiced concerns about signing a security pact with Japan, their one-time colonial ruler.  Besides historical issues stemming from Japan’s annexation of the Korean peninsula that ended in 1945, ties have been chilled by a long-running territorial dispute over a group of tiny islets.  ']